server:
  servlet:
    context-path: /person-queue-consumer-service

spring:
  application.name: person-queue-consumer-service

application:
  rabbitmq:
    queues:
      person: rabbitmq:personExchange?queue=person&concurrentConsumers=20&threadPoolSize=20&prefetchCount=10&prefetchSize=0&prefetchGlobal=false&prefetchEnabled=true

camel:
  component:
    rabbitmq:
      host: localhost
      port: 5672
      username: admin
      password: admin
      channel-pool-max-size: 20
      durable: true
      auto-delete: false
      auto-ack: false
  health:
    enabled: true
    check:
      routes:
        enabled: true
  springboot:
    main-run-controller: true
    name: person-queue-consumer-service


management:
  info:
    camel:
      enabled: true
